require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  DisplayCopNames: true
  Exclude:
    - bin/*
    - db/schema.rb
    - docker/*
    - db/migrate/202011*
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.0

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 124

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
  Max: 50

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

RSpec/AnyInstance:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false
