version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:9.6.5
    volumes:
      - ./tmp/db/pg_data:/var/lib/postgresql/data
    env_file:
      - '.env'
    ports:
      - "5432:5432"

  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"

  # sidekiq-web:
  #   container_name: sidekiq-web
  #   command: bundle exec rackup -o 0.0.0.0 -p 3001 sidekiq_web.ru
  #   build: .
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     - REDIS_URL=${ACTIVE_JOB_URL}
  #   env_file:
  #     - '.env'
  #   depends_on:
  #     - redis

volumes:
  redis:
  postgres:
